resteasy:
  jaxrs:
    app:
      registration: property
      classes: eu.fayder.restcountries.servlet.RestApplication
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - shutdown
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    org:
      springframework: info